version: "3"

services:
  ticket-mysql:
    image: mysql:8
    container_name: ticket-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 15_{!3R8Rci_
      MYSQL_DATABASE: ticket_system
    ports:
      - "3307:3306"
    volumes:
      - ticket-mysql-data:/var/lib/mysql
      - ./ticket_schema.sql:/docker-entrypoint-initdb.d/ticket_schema.sql

  backend:
    build:
      context: ./Ticket-Application-Backend
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    depends_on:
      - ticket-mysql

  frontend:
    build:
      context: ./Ticket-Application-Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

volumes:
  ticket-mysql-data:
